### ISSUE TITLE
Crashing when no phrase is passed

### ISSUE THREAD

**Issue by Lucxjo** [Lucxjo/Diru#1]
When no phrase is passed and the message isn't a reply, the bot crashes.

```
Environment: Docker
Bot version: 1.0.3
Self-hosted: ❌ 
```

<details>
<summary>Logs</summary>
panic: runtime error: index out of range [2] with length 2
goroutine 2989 [running]:
github.com/lucxjo/diru/cmd.Dpl(0xc00000c3c0, {0x7de4c0, 0xc00010cc60}, 0x1)
	/app/cmd/dpl.go:14 +0x305
github.com/lucxjo/diru/cmd.Commands(0xc00000c3c0, {0x7de4c0, 0xc00010cc60}, 0xc00001c200, {{0xc000116300, 0x3b}, {0xc00006e4b0, 0x24}, {{0xc000150140, 0x9b}, ...}})
	/app/cmd/commands.go:19 +0xa7
main.main.func2({0x7de4c0, 0xc00010cc60}, 0x20)
	/app/diru.go:39 +0x65
github.com/andersfylling/disgord.(*dispatcher).trigger(0xc0004ae0c0, {0x6f6080, 0xc0004ac050}, {0x71c1c0, 0xc0004046a0})
	/go/pkg/mod/github.com/andersfylling/disgord@v0.32.3/reactor_gen.go:621 +0x477
github.com/andersfylling/disgord.(*dispatcher).dispatch(0xc0000543c0, {0xc00001a970, 0xe}, {0x71c1c0, 0xc0004046a0})
	/go/pkg/mod/github.com/andersfylling/disgord@v0.32.3/reactor.go:148 +0x5ae
created by github.com/andersfylling/disgord.(*Client).demultiplexer
</details>

**Comment by Lucxjo** [comment]
Will be fixed in next release (v1.0.4).
