### ISSUE TITLE
Crashing on reply without function

### ISSUE THREAD

**Issue by Lucxjo** [Lucxjo/Diru#20]
The bot is crashing when someone uses it and mentions the bot without the `dpl*` or `gtr*` function. This only happens when replying to a message.

<details>
<summary><h3>Logs</h3></summary
panic: runtime error: index out of range [1] with length 1

goroutine 8926 [running]:
github.com/lucxjo/diru/cmd.Commands(0xc00000c1e0, {0x10796a0, 0xc00012f7a0}, 0xc00055a0a0, 0xc0000766c0, 0xc00012f7a0)
	/app/cmd/commands.go:39 +0x2112
main.main.func3({0x10796a0, 0xc00012f7a0}, 0x20)
	/app/diru.go:88 +0x46
github.com/andersfylling/disgord.(*dispatcher).trigger(0xc0004676e0, {0xd20580, 0xc0005784a0}, {0xd9ada0, 0xc000400050})
	/go/pkg/mod/github.com/andersfylling/disgord@v0.35.1/reactor_gen.go:621 +0x477
github.com/andersfylling/disgord.(*dispatcher).dispatch(0xc0000353c0, {0xc0005122f0, 0xe}, {0xd9ada0, 0xc000400050})
	/go/pkg/mod/github.com/andersfylling/disgord@v0.35.1/reactor.go:148 +0x5ae
created by github.com/andersfylling/disgord.(*Client).demultiplexer
	/go/pkg/mod/github.com/andersfylling/disgord@v0.35.1/reactor.go:70 +0x2cf
</details>

**Comment by Lucxjo** [comment]
@all-contributors please add @Lucxjo for bugs
